<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 4 Testing for differences between groups | Data Analysis Skills for Psychology in R</title>
  <meta name="description" content="This book contains the complete guide for computing tutorials for PSYC2001 at UNSW." />
  <meta name="generator" content="bookdown 0.37 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 4 Testing for differences between groups | Data Analysis Skills for Psychology in R" />
  <meta property="og:type" content="book" />
  <meta property="og:image" content="https://garner-code.github.io/PSYC2001_ComputingLabBook/images/cover_temp.png" />
  <meta property="og:description" content="This book contains the complete guide for computing tutorials for PSYC2001 at UNSW." />
  <meta name="github-repo" content="https://github.com/garner-code/PSYC2001_ComputingLabBook" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 4 Testing for differences between groups | Data Analysis Skills for Psychology in R" />
  
  <meta name="twitter:description" content="This book contains the complete guide for computing tutorials for PSYC2001 at UNSW." />
  <meta name="twitter:image" content="https://garner-code.github.io/PSYC2001_ComputingLabBook/images/cover_temp.png" />

<meta name="author" content="Kelly G. Garner, Bart Cooley, Marios Panayi, Peter Lovibond" />


<meta name="date" content="2026-01-23" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="sec-testing-first-hypothesis.html"/>
<link rel="next" href="probing-statistical-relationships-with-correlation-analysis.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">UNSW PSYC2001 Computing Tutorials</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Course Information</a>
<ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#the-purpose-of-this-coursebook"><i class="fa fa-check"></i><b>0.1</b> The purpose of this coursebook</a></li>
<li class="chapter" data-level="0.2" data-path="index.html"><a href="index.html#structure-of-the-coursebook"><i class="fa fa-check"></i><b>0.2</b> Structure of the Coursebook</a></li>
<li class="chapter" data-level="0.3" data-path="index.html"><a href="index.html#bugs-are-important"><i class="fa fa-check"></i><b>0.3</b> Bugs are important</a></li>
<li class="chapter" data-level="0.4" data-path="index.html"><a href="index.html#big-unknowns-and-little-unknowns"><i class="fa fa-check"></i><b>0.4</b> Big unknowns and little unknowns</a></li>
<li class="chapter" data-level="0.5" data-path="index.html"><a href="index.html#setting-up-r-and-rstudio"><i class="fa fa-check"></i><b>0.5</b> Setting up R and RStudio</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="introduction-to-r.html"><a href="introduction-to-r.html"><i class="fa fa-check"></i><b>1</b> Introduction to R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="introduction-to-r.html"><a href="introduction-to-r.html#r-and-r-studio"><i class="fa fa-check"></i><b>1.1</b> R and R Studio</a></li>
<li class="chapter" data-level="1.2" data-path="introduction-to-r.html"><a href="introduction-to-r.html#getting-started"><i class="fa fa-check"></i><b>1.2</b> Getting started</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="introduction-to-r.html"><a href="introduction-to-r.html#activity---setting-up-your-working-folder"><i class="fa fa-check"></i><b>1.2.1</b> Activity - Setting up your working folder</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="introduction-to-r.html"><a href="introduction-to-r.html#getting-to-know-r-studio"><i class="fa fa-check"></i><b>1.3</b> Getting to know R Studio</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="introduction-to-r.html"><a href="introduction-to-r.html#activity---using-the-console"><i class="fa fa-check"></i><b>1.3.1</b> Activity - Using the console</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="introduction-to-r.html"><a href="introduction-to-r.html#scripts"><i class="fa fa-check"></i><b>1.4</b> Scripts</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="introduction-to-r.html"><a href="introduction-to-r.html#sec-run-code"><i class="fa fa-check"></i><b>1.4.1</b> Activity - Getting to know scripts</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="introduction-to-r.html"><a href="introduction-to-r.html#sec-get-help"><i class="fa fa-check"></i><b>1.5</b> Functions and arguments</a>
<ul>
<li class="chapter" data-level="1.5.1" data-path="introduction-to-r.html"><a href="introduction-to-r.html#activity---using-a-function"><i class="fa fa-check"></i><b>1.5.1</b> Activity - using a function</a></li>
<li class="chapter" data-level="1.5.2" data-path="introduction-to-r.html"><a href="introduction-to-r.html#argument-names"><i class="fa fa-check"></i><b>1.5.2</b> Argument names</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="introduction-to-r.html"><a href="introduction-to-r.html#base-r-and-packages"><i class="fa fa-check"></i><b>1.6</b> Base R and packages</a></li>
<li class="chapter" data-level="1.7" data-path="introduction-to-r.html"><a href="introduction-to-r.html#installing-and-loading-packages"><i class="fa fa-check"></i><b>1.7</b> Installing and loading packages</a>
<ul>
<li class="chapter" data-level="1.7.1" data-path="introduction-to-r.html"><a href="introduction-to-r.html#activity---install-the-tidyverse"><i class="fa fa-check"></i><b>1.7.1</b> Activity - Install the tidyverse</a></li>
<li class="chapter" data-level="1.7.2" data-path="introduction-to-r.html"><a href="introduction-to-r.html#activity---load-the-tidyverse"><i class="fa fa-check"></i><b>1.7.2</b> Activity - Load the tidyverse</a></li>
</ul></li>
<li class="chapter" data-level="1.8" data-path="introduction-to-r.html"><a href="introduction-to-r.html#objects"><i class="fa fa-check"></i><b>1.8</b> Objects</a>
<ul>
<li class="chapter" data-level="1.8.1" data-path="introduction-to-r.html"><a href="introduction-to-r.html#sec-make-objects"><i class="fa fa-check"></i><b>1.8.1</b> Activity - Create some objects</a></li>
</ul></li>
<li class="chapter" data-level="1.9" data-path="introduction-to-r.html"><a href="introduction-to-r.html#datatypes"><i class="fa fa-check"></i><b>1.9</b> Datatypes</a>
<ul>
<li class="chapter" data-level="1.9.1" data-path="introduction-to-r.html"><a href="introduction-to-r.html#sec-data-type"><i class="fa fa-check"></i><b>1.9.1</b> Activity - Explore datatypes</a></li>
</ul></li>
<li class="chapter" data-level="1.10" data-path="introduction-to-r.html"><a href="introduction-to-r.html#looking-after-the-environment"><i class="fa fa-check"></i><b>1.10</b> Looking after the environment</a></li>
<li class="chapter" data-level="1.11" data-path="introduction-to-r.html"><a href="introduction-to-r.html#the-power-of-scripts"><i class="fa fa-check"></i><b>1.11</b> The power of scripts</a>
<ul>
<li class="chapter" data-level="1.11.1" data-path="introduction-to-r.html"><a href="introduction-to-r.html#final-activity---run-the-script"><i class="fa fa-check"></i><b>1.11.1</b> Final Activity - Run the script</a></li>
</ul></li>
<li class="chapter" data-level="1.12" data-path="introduction-to-r.html"><a href="introduction-to-r.html#you-are-free"><i class="fa fa-check"></i><b>1.12</b> You are Free!</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html"><i class="fa fa-check"></i><b>2</b> Data wrangling and visualisation</a>
<ul>
<li class="chapter" data-level="2.1" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#checking-installation-and-loading-packages"><i class="fa fa-check"></i><b>2.1</b> Checking installation and loading packages</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#activity---load-your-packages"><i class="fa fa-check"></i><b>2.1.1</b> Activity - Load your packages</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#what-do-packages-do"><i class="fa fa-check"></i><b>2.2</b> What do packages do?</a></li>
<li class="chapter" data-level="2.3" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#what-do-these-packages-do"><i class="fa fa-check"></i><b>2.3</b> What do these packages do?</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#activity---find-out-about-packages"><i class="fa fa-check"></i><b>2.3.1</b> Activity - find out about packages</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#organisation-and-csv-files"><i class="fa fa-check"></i><b>2.4</b> Organisation and CSV files</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#activity---getting-to-know-the-data-files"><i class="fa fa-check"></i><b>2.4.1</b> Activity - getting to know the data files</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#importing-your-data-in-r"><i class="fa fa-check"></i><b>2.5</b> Importing your Data in R</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#sec-import-data"><i class="fa fa-check"></i><b>2.5.1</b> Activity - Import the data</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#having-a-look-at-our-data"><i class="fa fa-check"></i><b>2.6</b> Having a look at our data</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#sec-data-view"><i class="fa fa-check"></i><b>2.6.1</b> Activity - View the data. Always, always, view the data.</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#checking-the-quality-of-our-data"><i class="fa fa-check"></i><b>2.7</b> Checking the quality of our data</a>
<ul>
<li class="chapter" data-level="2.7.1" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#activity---summarise-the-data"><i class="fa fa-check"></i><b>2.7.1</b> Activity - Summarise the data</a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#cleaning-the-data"><i class="fa fa-check"></i><b>2.8</b> Cleaning the data</a>
<ul>
<li class="chapter" data-level="2.8.1" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#activity---find-and-replace--999-values"><i class="fa fa-check"></i><b>2.8.1</b> Activity - Find and replace <code>-999</code> values</a></li>
</ul></li>
<li class="chapter" data-level="2.9" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#introducing-piping"><i class="fa fa-check"></i><b>2.9</b> Introducing Piping</a>
<ul>
<li class="chapter" data-level="2.9.1" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#sec-pipey"><i class="fa fa-check"></i><b>2.9.1</b> Activity - Pipe with pipes</a></li>
</ul></li>
<li class="chapter" data-level="2.10" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#exporting-data"><i class="fa fa-check"></i><b>2.10</b> Exporting Data</a>
<ul>
<li class="chapter" data-level="2.10.1" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#sec-save-the-data"><i class="fa fa-check"></i><b>2.10.1</b> Activity - Save the cleaned data</a></li>
</ul></li>
<li class="chapter" data-level="2.11" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#data-visualization-using-ggplot"><i class="fa fa-check"></i><b>2.11</b> Data visualization using <code>ggplot()</code></a>
<ul>
<li class="chapter" data-level="2.11.1" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#sec-make-bp"><i class="fa fa-check"></i><b>2.11.1</b> Activity - Starting a canvas in <code>ggplot()</code></a></li>
<li class="chapter" data-level="2.11.2" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#activity---add-a-boxplot-to-the-canvas"><i class="fa fa-check"></i><b>2.11.2</b> Activity - Add a boxplot to the canvas</a></li>
<li class="chapter" data-level="2.11.3" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#activity---tidy-up-the-x-axis"><i class="fa fa-check"></i><b>2.11.3</b> Activity - tidy up the x-axis</a></li>
<li class="chapter" data-level="2.11.4" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#activity---add-some-labels"><i class="fa fa-check"></i><b>2.11.4</b> Activity - add some labels</a></li>
<li class="chapter" data-level="2.11.5" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#sec-make-histogram"><i class="fa fa-check"></i><b>2.11.5</b> Activity - More data-viz, more better - Creating a histogram in <code>ggplot()</code></a></li>
</ul></li>
<li class="chapter" data-level="2.12" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#you-are-free-1"><i class="fa fa-check"></i><b>2.12</b> You are Free!</a></li>
<li class="chapter" data-level="2.13" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#bonus-exercises"><i class="fa fa-check"></i><b>2.13</b> ⭐ Bonus exercises</a>
<ul>
<li class="chapter" data-level="2.13.1" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#bonus-exercise---a-bit-more-wrangling"><i class="fa fa-check"></i><b>2.13.1</b> Bonus exercise - a bit more wrangling</a></li>
<li class="chapter" data-level="2.13.2" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#bonus-exercise---getting-to-grips-with-graphs"><i class="fa fa-check"></i><b>2.13.2</b> Bonus exercise - getting to grips with graphs</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="sec-testing-first-hypothesis.html"><a href="sec-testing-first-hypothesis.html"><i class="fa fa-check"></i><b>3</b> Testing our first hypothesis</a>
<ul>
<li class="chapter" data-level="3.1" data-path="sec-testing-first-hypothesis.html"><a href="sec-testing-first-hypothesis.html#checking-installation-and-loading-packages-1"><i class="fa fa-check"></i><b>3.1</b> Checking installation and loading packages</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="sec-testing-first-hypothesis.html"><a href="sec-testing-first-hypothesis.html#activity---load-packages-using-the-library-function"><i class="fa fa-check"></i><b>3.1.1</b> Activity - Load packages using the <code>library()</code> function</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="sec-testing-first-hypothesis.html"><a href="sec-testing-first-hypothesis.html#developing-our-hypotheses"><i class="fa fa-check"></i><b>3.2</b> Developing our hypotheses</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="sec-testing-first-hypothesis.html"><a href="sec-testing-first-hypothesis.html#activity---defining-our-hypotheses"><i class="fa fa-check"></i><b>3.2.1</b> Activity - Defining our hypotheses</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="sec-testing-first-hypothesis.html"><a href="sec-testing-first-hypothesis.html#loading-our-data-ready-for-visualisation-and-analysis"><i class="fa fa-check"></i><b>3.3</b> Loading our data ready for visualisation and analysis</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="sec-testing-first-hypothesis.html"><a href="sec-testing-first-hypothesis.html#activity---loading-in-the-data"><i class="fa fa-check"></i><b>3.3.1</b> Activity - Loading in the data</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="sec-testing-first-hypothesis.html"><a href="sec-testing-first-hypothesis.html#visualising-is-important"><i class="fa fa-check"></i><b>3.4</b> Visualising is important</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="sec-testing-first-hypothesis.html"><a href="sec-testing-first-hypothesis.html#sec-get-back-on-the-pipes"><i class="fa fa-check"></i><b>3.4.1</b> Activity - Get back on the pipes!</a></li>
<li class="chapter" data-level="3.4.2" data-path="sec-testing-first-hypothesis.html"><a href="sec-testing-first-hypothesis.html#sec-densities"><i class="fa fa-check"></i><b>3.4.2</b> Activity - start plotting</a></li>
<li class="chapter" data-level="3.4.3" data-path="sec-testing-first-hypothesis.html"><a href="sec-testing-first-hypothesis.html#sec-visualised-now-what"><i class="fa fa-check"></i><b>3.4.3</b> Activity - So you’ve visualised your data, now what?</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="sec-testing-first-hypothesis.html"><a href="sec-testing-first-hypothesis.html#descriptive-statistics"><i class="fa fa-check"></i><b>3.5</b> Descriptive statistics</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="sec-testing-first-hypothesis.html"><a href="sec-testing-first-hypothesis.html#sec-get-descriptive"><i class="fa fa-check"></i><b>3.5.1</b> Activity - get descriptive!</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="sec-testing-first-hypothesis.html"><a href="sec-testing-first-hypothesis.html#testing-hypotheses-manually"><i class="fa fa-check"></i><b>3.6</b> Testing hypotheses manually</a></li>
<li class="chapter" data-level="3.7" data-path="sec-testing-first-hypothesis.html"><a href="sec-testing-first-hypothesis.html#testing-hypothesis-using-a-paired-sample-t-test"><i class="fa fa-check"></i><b>3.7</b> Testing hypothesis using a paired-sample t-test</a>
<ul>
<li class="chapter" data-level="3.7.1" data-path="sec-testing-first-hypothesis.html"><a href="sec-testing-first-hypothesis.html#sec-conducting-paired-t-test"><i class="fa fa-check"></i><b>3.7.1</b> Activity - Conducting a paired t-test</a></li>
</ul></li>
<li class="chapter" data-level="3.8" data-path="sec-testing-first-hypothesis.html"><a href="sec-testing-first-hypothesis.html#you-are-free-2"><i class="fa fa-check"></i><b>3.8</b> You are Free!</a></li>
<li class="chapter" data-level="3.9" data-path="sec-testing-first-hypothesis.html"><a href="sec-testing-first-hypothesis.html#bonus-exercises-1"><i class="fa fa-check"></i><b>3.9</b> ⭐ Bonus exercises</a>
<ul>
<li class="chapter" data-level="3.9.1" data-path="sec-testing-first-hypothesis.html"><a href="sec-testing-first-hypothesis.html#bonus-activity---correspondence-to-one-sample-t-tests"><i class="fa fa-check"></i><b>3.9.1</b> Bonus Activity - Correspondence to one-sample t-tests</a></li>
<li class="chapter" data-level="3.9.2" data-path="sec-testing-first-hypothesis.html"><a href="sec-testing-first-hypothesis.html#bonus-activity---visualising-differences-in-paired-data"><i class="fa fa-check"></i><b>3.9.2</b> Bonus Activity - visualising differences in paired data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="testing-for-differences-between-groups.html"><a href="testing-for-differences-between-groups.html"><i class="fa fa-check"></i><b>4</b> Testing for differences between groups</a>
<ul>
<li class="chapter" data-level="4.1" data-path="testing-for-differences-between-groups.html"><a href="testing-for-differences-between-groups.html#checking-installation-and-loading-packages-2"><i class="fa fa-check"></i><b>4.1</b> Checking installation and loading packages</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="testing-for-differences-between-groups.html"><a href="testing-for-differences-between-groups.html#activity---load-packages-using-library"><i class="fa fa-check"></i><b>4.1.1</b> Activity - load packages using <code>library()</code></a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="testing-for-differences-between-groups.html"><a href="testing-for-differences-between-groups.html#how-does-where-you-live-impact-how-you-use-social-media"><i class="fa fa-check"></i><b>4.2</b> How does where you live impact how you use social media?</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="testing-for-differences-between-groups.html"><a href="testing-for-differences-between-groups.html#activity---formulate-your-research-question"><i class="fa fa-check"></i><b>4.2.1</b> Activity - Formulate your research question</a></li>
<li class="chapter" data-level="4.2.2" data-path="testing-for-differences-between-groups.html"><a href="testing-for-differences-between-groups.html#activity---load-in-data-and-check-it"><i class="fa fa-check"></i><b>4.2.2</b> Activity - Load in data and check it</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="testing-for-differences-between-groups.html"><a href="testing-for-differences-between-groups.html#wrangling-our-data"><i class="fa fa-check"></i><b>4.3</b> Wrangling our data</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="testing-for-differences-between-groups.html"><a href="testing-for-differences-between-groups.html#sec-new-likes"><i class="fa fa-check"></i><b>4.3.1</b> Activity - Creating a new <code>likes</code> variable</a></li>
<li class="chapter" data-level="4.3.2" data-path="testing-for-differences-between-groups.html"><a href="testing-for-differences-between-groups.html#activity---defining-factors"><i class="fa fa-check"></i><b>4.3.2</b> Activity - Defining factors</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="testing-for-differences-between-groups.html"><a href="testing-for-differences-between-groups.html#visualising-our-data"><i class="fa fa-check"></i><b>4.4</b> Visualising our data</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="testing-for-differences-between-groups.html"><a href="testing-for-differences-between-groups.html#activity---adapting-our-previous-code-to-make-new-histograms"><i class="fa fa-check"></i><b>4.4.1</b> Activity - Adapting our previous code to make new histograms</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="testing-for-differences-between-groups.html"><a href="testing-for-differences-between-groups.html#next-step-descriptive-statistics"><i class="fa fa-check"></i><b>4.5</b> Next step: descriptive statistics</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="testing-for-differences-between-groups.html"><a href="testing-for-differences-between-groups.html#activity---adapt-the-code-to-get-the-mean-and-standard-deviations-for-likes-and-followers"><i class="fa fa-check"></i><b>4.5.1</b> Activity - Adapt the code to get the mean and standard deviations for likes and followers</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="testing-for-differences-between-groups.html"><a href="testing-for-differences-between-groups.html#independent-samples-t-test"><i class="fa fa-check"></i><b>4.6</b> Independent samples t-test</a>
<ul>
<li class="chapter" data-level="4.6.1" data-path="testing-for-differences-between-groups.html"><a href="testing-for-differences-between-groups.html#sec-formula-for-independence"><i class="fa fa-check"></i><b>4.6.1</b> Activity - Performing independent samples t-tests</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="testing-for-differences-between-groups.html"><a href="testing-for-differences-between-groups.html#writing-up-results-and-conclusions"><i class="fa fa-check"></i><b>4.7</b> Writing up results and conclusions</a>
<ul>
<li class="chapter" data-level="4.7.1" data-path="testing-for-differences-between-groups.html"><a href="testing-for-differences-between-groups.html#activity---visualising-group-differences"><i class="fa fa-check"></i><b>4.7.1</b> Activity - Visualising group differences</a></li>
</ul></li>
<li class="chapter" data-level="4.8" data-path="testing-for-differences-between-groups.html"><a href="testing-for-differences-between-groups.html#you-are-free-3"><i class="fa fa-check"></i><b>4.8</b> You are Free!</a></li>
<li class="chapter" data-level="4.9" data-path="testing-for-differences-between-groups.html"><a href="testing-for-differences-between-groups.html#bonus-exercises-2"><i class="fa fa-check"></i><b>4.9</b> ⭐ Bonus exercises</a>
<ul>
<li class="chapter" data-level="4.9.1" data-path="testing-for-differences-between-groups.html"><a href="testing-for-differences-between-groups.html#bonus-activity---new-variable"><i class="fa fa-check"></i><b>4.9.1</b> Bonus Activity - new variable!</a></li>
<li class="chapter" data-level="4.9.2" data-path="testing-for-differences-between-groups.html"><a href="testing-for-differences-between-groups.html#bonus-activity---visualising-group-means"><i class="fa fa-check"></i><b>4.9.2</b> Bonus Activity - Visualising group means</a></li>
<li class="chapter" data-level="4.9.3" data-path="testing-for-differences-between-groups.html"><a href="testing-for-differences-between-groups.html#bonus-activity---tracking-bugs"><i class="fa fa-check"></i><b>4.9.3</b> Bonus Activity - Tracking bugs</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="probing-statistical-relationships-with-correlation-analysis.html"><a href="probing-statistical-relationships-with-correlation-analysis.html"><i class="fa fa-check"></i><b>5</b> Probing (Statistical) Relationships with Correlation Analysis</a>
<ul>
<li class="chapter" data-level="5.1" data-path="probing-statistical-relationships-with-correlation-analysis.html"><a href="probing-statistical-relationships-with-correlation-analysis.html#checking-installation-and-loading-packages-3"><i class="fa fa-check"></i><b>5.1</b> Checking installation and loading packages</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="probing-statistical-relationships-with-correlation-analysis.html"><a href="probing-statistical-relationships-with-correlation-analysis.html#activity---write-the-code-to-load-packages-from-the-library"><i class="fa fa-check"></i><b>5.1.1</b> Activity - write the code to load packages from the library</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="probing-statistical-relationships-with-correlation-analysis.html"><a href="probing-statistical-relationships-with-correlation-analysis.html#investigating-correlational-relationships"><i class="fa fa-check"></i><b>5.2</b> Investigating correlational relationships</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="probing-statistical-relationships-with-correlation-analysis.html"><a href="probing-statistical-relationships-with-correlation-analysis.html#activity---how-might-political-attitudes-relate-to-social-media-use-get-data"><i class="fa fa-check"></i><b>5.2.1</b> Activity - How might political attitudes relate to social media use? Get Data</a></li>
<li class="chapter" data-level="5.2.2" data-path="probing-statistical-relationships-with-correlation-analysis.html"><a href="probing-statistical-relationships-with-correlation-analysis.html#activity---noting-down-your-hypotheses"><i class="fa fa-check"></i><b>5.2.2</b> Activity - Noting down your hypotheses</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="probing-statistical-relationships-with-correlation-analysis.html"><a href="probing-statistical-relationships-with-correlation-analysis.html#building-a-composite-score-that-measures-political-attitude"><i class="fa fa-check"></i><b>5.3</b> Building a composite score that measures political attitude</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="probing-statistical-relationships-with-correlation-analysis.html"><a href="probing-statistical-relationships-with-correlation-analysis.html#activity---get-some-political-attitude"><i class="fa fa-check"></i><b>5.3.1</b> Activity - Get some political attitude</a></li>
<li class="chapter" data-level="5.3.2" data-path="probing-statistical-relationships-with-correlation-analysis.html"><a href="probing-statistical-relationships-with-correlation-analysis.html#sec-select-and-save"><i class="fa fa-check"></i><b>5.3.2</b> Activity - save the results of your hard work</a></li>
<li class="chapter" data-level="5.3.3" data-path="probing-statistical-relationships-with-correlation-analysis.html"><a href="probing-statistical-relationships-with-correlation-analysis.html#sec-scatterplots"><i class="fa fa-check"></i><b>5.3.3</b> Activity - Scatterplots to visualise relationships (in the hunt for straight-ish lines)</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="probing-statistical-relationships-with-correlation-analysis.html"><a href="probing-statistical-relationships-with-correlation-analysis.html#conducting-correlations"><i class="fa fa-check"></i><b>5.4</b> Conducting correlations</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="probing-statistical-relationships-with-correlation-analysis.html"><a href="probing-statistical-relationships-with-correlation-analysis.html#calculate-the-correlation-coefficient"><i class="fa fa-check"></i><b>5.4.1</b> Calculate the correlation coefficient</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="probing-statistical-relationships-with-correlation-analysis.html"><a href="probing-statistical-relationships-with-correlation-analysis.html#testing-the-statistical-significance-of-the-correlation-coefficient"><i class="fa fa-check"></i><b>5.5</b> Testing the statistical significance of the correlation coefficient</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="probing-statistical-relationships-with-correlation-analysis.html"><a href="probing-statistical-relationships-with-correlation-analysis.html#sec-cor-form"><i class="fa fa-check"></i><b>5.5.1</b> Activity - correlation using the formula method</a></li>
<li class="chapter" data-level="5.5.2" data-path="probing-statistical-relationships-with-correlation-analysis.html"><a href="probing-statistical-relationships-with-correlation-analysis.html#activity---correlation-using-base-r-syntax"><i class="fa fa-check"></i><b>5.5.2</b> Activity - correlation using base R syntax</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="probing-statistical-relationships-with-correlation-analysis.html"><a href="probing-statistical-relationships-with-correlation-analysis.html#writing-up-results-and-conclusions-1"><i class="fa fa-check"></i><b>5.6</b> Writing up results and conclusions</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="probing-statistical-relationships-with-correlation-analysis.html"><a href="probing-statistical-relationships-with-correlation-analysis.html#activity---correlation-for-the-other-pair-of-variables"><i class="fa fa-check"></i><b>5.6.1</b> Activity - Correlation for the other pair of variables</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="probing-statistical-relationships-with-correlation-analysis.html"><a href="probing-statistical-relationships-with-correlation-analysis.html#you-are-free-4"><i class="fa fa-check"></i><b>5.7</b> You are Free!</a></li>
<li class="chapter" data-level="5.8" data-path="probing-statistical-relationships-with-correlation-analysis.html"><a href="probing-statistical-relationships-with-correlation-analysis.html#bonus-exercises-3"><i class="fa fa-check"></i><b>5.8</b> ⭐ Bonus exercises</a>
<ul>
<li class="chapter" data-level="5.8.1" data-path="probing-statistical-relationships-with-correlation-analysis.html"><a href="probing-statistical-relationships-with-correlation-analysis.html#bonus-activity---urban-vs-rural-correlations"><i class="fa fa-check"></i><b>5.8.1</b> Bonus Activity - Urban vs Rural Correlations</a></li>
<li class="chapter" data-level="5.8.2" data-path="probing-statistical-relationships-with-correlation-analysis.html"><a href="probing-statistical-relationships-with-correlation-analysis.html#bonus-activity---piping-out-a-summary-of-correlations-for-urban-vs-rural-groups"><i class="fa fa-check"></i><b>5.8.2</b> Bonus Activity - Piping out a summary of correlations for Urban vs Rural groups</a></li>
<li class="chapter" data-level="5.8.3" data-path="probing-statistical-relationships-with-correlation-analysis.html"><a href="probing-statistical-relationships-with-correlation-analysis.html#bonus-activity---correlation-matrix"><i class="fa fa-check"></i><b>5.8.3</b> Bonus Activity - Correlation Matrix</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="linear-regression.html"><a href="linear-regression.html"><i class="fa fa-check"></i><b>6</b> Making predicitions using Linear Regression</a>
<ul>
<li class="chapter" data-level="6.1" data-path="linear-regression.html"><a href="linear-regression.html#checking-installation-and-loading-packages-4"><i class="fa fa-check"></i><b>6.1</b> Checking installation and loading packages</a></li>
<li class="chapter" data-level="6.2" data-path="linear-regression.html"><a href="linear-regression.html#investigating-linear-regressions"><i class="fa fa-check"></i><b>6.2</b> Investigating linear regressions</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="linear-regression.html"><a href="linear-regression.html#activity---formulate-your-prediction-about-predictions"><i class="fa fa-check"></i><b>6.2.1</b> Activity - Formulate your prediction about predictions</a></li>
<li class="chapter" data-level="6.2.2" data-path="linear-regression.html"><a href="linear-regression.html#activity---loading-the-data-set"><i class="fa fa-check"></i><b>6.2.2</b> Activity - loading the data set</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="linear-regression.html"><a href="linear-regression.html#lets-get-the-data-into-shape-for-some-viz"><i class="fa fa-check"></i><b>6.3</b> Let`s get the data into shape for some viz</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="linear-regression.html"><a href="linear-regression.html#activity---select-and-pivot-to-longform"><i class="fa fa-check"></i><b>6.3.1</b> Activity - select and pivot to longform</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="linear-regression.html"><a href="linear-regression.html#linear-regression-in-r"><i class="fa fa-check"></i><b>6.4</b> Linear regression in R</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="linear-regression.html"><a href="linear-regression.html#activity---fitting-a-linear-regression-model"><i class="fa fa-check"></i><b>6.4.1</b> Activity - fitting a linear regression model</a></li>
<li class="chapter" data-level="6.4.2" data-path="linear-regression.html"><a href="linear-regression.html#activity---how-good-is-our-model"><i class="fa fa-check"></i><b>6.4.2</b> Activity - how good is our model?</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="linear-regression.html"><a href="linear-regression.html#writing-up-results-and-conclusions-2"><i class="fa fa-check"></i><b>6.5</b> Writing up results and conclusions</a></li>
<li class="chapter" data-level="6.6" data-path="linear-regression.html"><a href="linear-regression.html#plotting-our-results"><i class="fa fa-check"></i><b>6.6</b> Plotting our results</a>
<ul>
<li class="chapter" data-level="6.6.1" data-path="linear-regression.html"><a href="linear-regression.html#activity---adding-a-line-of-best-fit-to-a-scatterplot"><i class="fa fa-check"></i><b>6.6.1</b> Activity - Adding a line of best fit to a scatterplot</a></li>
<li class="chapter" data-level="6.6.2" data-path="linear-regression.html"><a href="linear-regression.html#activity---level-up"><i class="fa fa-check"></i><b>6.6.2</b> Activity - level up</a></li>
</ul></li>
<li class="chapter" data-level="6.7" data-path="linear-regression.html"><a href="linear-regression.html#you-are-free-5"><i class="fa fa-check"></i><b>6.7</b> You are Free!</a></li>
<li class="chapter" data-level="6.8" data-path="linear-regression.html"><a href="linear-regression.html#bonus-exercises-4"><i class="fa fa-check"></i><b>6.8</b> ⭐ Bonus exercises</a>
<ul>
<li class="chapter" data-level="6.8.1" data-path="linear-regression.html"><a href="linear-regression.html#bonus-activity---tidying-up-the-scatterplot"><i class="fa fa-check"></i><b>6.8.1</b> Bonus Activity - Tidying up the Scatterplot</a></li>
<li class="chapter" data-level="6.8.2" data-path="linear-regression.html"><a href="linear-regression.html#bonus-activity---visualising-the-line-of-best-fit-for-urban-and-rural-participants-on-seperate-plots"><i class="fa fa-check"></i><b>6.8.2</b> Bonus Activity - Visualising the line of best fit for Urban and Rural participants on seperate plots</a></li>
<li class="chapter" data-level="6.8.3" data-path="linear-regression.html"><a href="linear-regression.html#final-bonus-activity---can-you-fix-the-bug-to-make-this-code-work"><i class="fa fa-check"></i><b>6.8.3</b> Final Bonus Activity - Can you fix the bug to make this code work?</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Data Analysis Skills for Psychology in R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="testing-for-differences-between-groups" class="section level1 hasAnchor" number="4">
<h1><span class="header-section-number">Chapter 4</span> Testing for differences between groups<a href="testing-for-differences-between-groups.html#testing-for-differences-between-groups" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>This week we will be learning how to conduct an independent samples t-test. This is a statistical test that allows us to compare the means of two independent groups on a continuous outcome variable. According to the 90/10 theorem, we will spend 90% of our time wrangling and visualising our data, and 10% of our time actually conducting the t-test.</p>
<div id="checking-installation-and-loading-packages-2" class="section level2 hasAnchor" number="4.1">
<h2><span class="header-section-number">4.1</span> Checking installation and loading packages<a href="testing-for-differences-between-groups.html#checking-installation-and-loading-packages-2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>As usual we first always check and load in our required packages.</p>
<div id="activity---load-packages-using-library" class="section level3 hasAnchor" number="4.1.1">
<h3><span class="header-section-number">4.1.1</span> Activity - load packages using <code>library()</code><a href="testing-for-differences-between-groups.html#activity---load-packages-using-library" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Just like in Chapter <a href="sec-testing-first-hypothesis.html#sec-testing-first-hypothesis">3</a>, your script contains the code to install the packages, if required.</p>
<blockquote>
<p>Add the two lines of code that use the <code>library()</code> function to load <code>here</code> and <code>tidyverse</code> to your own script. Run all the code.</p>
</blockquote>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="testing-for-differences-between-groups.html#cb71-1" tabindex="-1"></a><span class="co"># Check if packages are installed, if not install.</span></span>
<span id="cb71-2"><a href="testing-for-differences-between-groups.html#cb71-2" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(here)) <span class="fu">install.packages</span>(<span class="st">&#39;here&#39;</span>) <span class="co">#checks if a package is installed and installs it if required.</span></span>
<span id="cb71-3"><a href="testing-for-differences-between-groups.html#cb71-3" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(tidyverse)) <span class="fu">install.packages</span>(<span class="st">&#39;tidyverse&#39;</span>)</span>
<span id="cb71-4"><a href="testing-for-differences-between-groups.html#cb71-4" tabindex="-1"></a></span>
<span id="cb71-5"><a href="testing-for-differences-between-groups.html#cb71-5" tabindex="-1"></a><span class="fu">library</span>(here) <span class="co">#loads in the specified package</span></span>
<span id="cb71-6"><a href="testing-for-differences-between-groups.html#cb71-6" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div>
</div>
</div>
<div id="how-does-where-you-live-impact-how-you-use-social-media" class="section level2 hasAnchor" number="4.2">
<h2><span class="header-section-number">4.2</span> How does where you live impact how you use social media?<a href="testing-for-differences-between-groups.html#how-does-where-you-live-impact-how-you-use-social-media" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In Chapter <a href="sec-testing-first-hypothesis.html#sec-testing-first-hypothesis">3</a>, we performed an analysis to learn how mood impacts active social media behaviour. However, that is not the only factor that influences social media use. For example, <a href="https://academic.oup.com/pnasnexus/article/2/11/pgad357/7442564">Sapienza et al (2023)</a> found that people in rural areas are more likely to use their smartphone for social media and gaming, whereas urban dwellers are more likely to use their phone for navigation and business.</p>
<p>However, we do not know if people living in urban and rural areas engage with social media differently, regardless of how long they spend on their chosen platforms. Today we will address this question using the <code>urban</code>, <code>good_mood_likes</code>, <code>bad_mood_likes</code>, and <code>followers</code> variables. Remember, these variables stand for the following:</p>
<p><code>urban</code> – urban (1) or rural (2) area (based on postcode density)<br />
<code>good_mood_likes</code> – average number of likes made over 10 min during a good mood (from platform + diary)<br />
<code>bad_mood_likes</code> – as above, but during bad mood<br />
<code>followers</code> – average number of followers across platforms</p>
<div id="activity---formulate-your-research-question" class="section level3 hasAnchor" number="4.2.1">
<h3><span class="header-section-number">4.2.1</span> Activity - Formulate your research question<a href="testing-for-differences-between-groups.html#activity---formulate-your-research-question" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>What do you think? Will urban and rural dwellers engage differently with social media? Why might you go on social media if you were somewhere rural compared to urban? Will there be a difference in the number of likes made by people living in urban vs rural areas? Or in the number of followers people have in urban vs rural areas?</p>
<div style="border-left: 4px solid #33a02c; background-color: #a6cee3; padding: 10px; margin: 10px 0;">
<p><strong>Extra info:</strong> We are going to average over the effect of mood, so we do not need to include mood in our predictions about likes.</p>
</div>
<blockquote>
<p>Write down your answers to the these questions as a comment in your script.</p>
</blockquote>
<div style="border-left: 4px solid #33a02c; background-color: #a6cee3; padding: 10px; margin: 10px 0;">
<p><strong>Question:</strong> What are the null and alternate hypothesis for your research questions (you should have one for ‘likes’ and one for ‘followers’). Write these as a comment in your script.</p>
</div>
</div>
<div id="activity---load-in-data-and-check-it" class="section level3 hasAnchor" number="4.2.2">
<h3><span class="header-section-number">4.2.2</span> Activity - Load in data and check it<a href="testing-for-differences-between-groups.html#activity---load-in-data-and-check-it" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Today we will be averaging across mood to get the number of likes for urban and rural dwellers. This means we first need to create a new variable called <code>likes</code> which is the average of the likes in a good and bad mood.</p>
<p>We first load in our<code>PSYC2001_social-media-data-cleaned.csv</code> dataset.</p>
<blockquote>
<p>Copy and paste this code into your script and run it to load in the data.</p>
</blockquote>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="testing-for-differences-between-groups.html#cb72-1" tabindex="-1"></a>social_media <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="at">file =</span> <span class="fu">here</span>(<span class="st">&quot;Data&quot;</span>,<span class="st">&quot;PSYC2001_social-media-data-cleaned.csv&quot;</span>)) <span class="co">#reads in CSV files</span></span></code></pre></div>
<p>Lets double check its the data we think it is by using the <code>head()</code> function. See that we’ve added in an argument to say we want to see the first 10 lines of the data.</p>
<blockquote>
<p>Amend your code in your script to look at the number of rows your very own eyes want to see.</p>
</blockquote>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="testing-for-differences-between-groups.html#cb73-1" tabindex="-1"></a><span class="fu">head</span>(social_media, <span class="dv">10</span>) <span class="co"># you can even say how many lines you want to see! Try changing the number, and see what happens.</span></span></code></pre></div>
<pre><code>##     X  id  age time_on_social urban good_mood_likes bad_mood_likes
## 1   1  S1 15.2           3.06     1            22.8           46.5
## 2   2  S2 16.0           2.18     1            46.0           48.3
## 3   3  S3 16.8           1.92     1            50.8           46.1
## 4   4  S4 15.6           2.61     1            29.9           29.2
## 5   5  S5 17.1           3.24     1            37.1           52.4
## 6   6  S6 15.7           2.44     1            26.9           20.2
## 7   7  S7 19.7           1.46     1            14.8           35.1
## 8   8  S8 18.6           1.52     1            26.0           35.8
## 9   9  S9 19.6           1.92     1             6.5           12.2
## 10 10 S10 15.5           2.10     1            45.7           32.8
##    followers polit_informed polit_campaign polit_activism
## 1      173.3            2.3            3.2            3.6
## 2      144.3            1.6            2.2            2.6
## 3       76.5            1.9            2.7            3.0
## 4      171.7            1.6            2.3            2.6
## 5      109.5            2.0            2.9            3.3
## 6      157.5            2.4            3.4            3.9
## 7      166.9            1.7            2.4            2.7
## 8      109.6            1.6            2.2            2.6
## 9      253.4            1.5            2.1            2.4
## 10      77.2            2.2            3.1            3.5</code></pre>
</div>
</div>
<div id="wrangling-our-data" class="section level2 hasAnchor" number="4.3">
<h2><span class="header-section-number">4.3</span> Wrangling our data<a href="testing-for-differences-between-groups.html#wrangling-our-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>There are a couple of things we need to do to get our data into shape. The first is to create our new variable <code>likes</code> which is the average of <code>good_mood_likes</code> and <code>bad_mood_likes</code>. The second is to define the urban factor correctly. More on that to come!</p>
<div id="sec-new-likes" class="section level3 hasAnchor" number="4.3.1">
<h3><span class="header-section-number">4.3.1</span> Activity - Creating a new <code>likes</code> variable<a href="testing-for-differences-between-groups.html#sec-new-likes" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We need to create a new variable called <code>likes</code> which is the average of <code>good_mood_likes</code> and <code>bad_mood_likes</code>. To do this, we are going to use the <code>mutate()</code> function from the <code>tidyverse</code> package. You can think of using <code>mutate()</code> as a way to create a new column in your data frame, using information from other columns.</p>
<p>To use <code>mutate()</code> we need to use the pipe operator <code>%&gt;%</code> which we also used in Section <a href="sec-testing-first-hypothesis.html#sec-get-back-on-the-pipes">3.4.1</a>. The pipe operator takes the output of one function and uses it as the input for the next function. This is very useful when we want to do multiple things to a data frame in a single line of code.</p>
<p>We are going to use the pipe operator to take the <code>social_media</code> data frame and then use <code>mutate()</code> to create our new variable <code>likes</code>. Because we want the average likes, we will add <code>good_mood_likes</code> and <code>bad_mood_likes</code> together and then divide by 2.</p>
<p>Because this is a new way of using code, we need to carefully design a test that tells us if our code is working as it should. <strong>This is a very important part of coding.</strong> In this case, the test is very easy to design. We can manually calculate the first few values of <code>likes</code> that our code should produce. Then, if our code does indeed produce those values, we know exactly what our code is doing.</p>
<blockquote>
<p>Using the console (or in your head), calculate what values you should get for the first three rows of the <code>likes</code> column, when taking the average of <code>bad_mood_likes</code> and <code>good_mood_likes</code>. Add these values as comments to your script.</p>
</blockquote>
<blockquote>
<p>Now, get the whole column of averages by running the following line of code in your script.</p>
</blockquote>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="testing-for-differences-between-groups.html#cb75-1" tabindex="-1"></a>social_media_likes <span class="ot">&lt;-</span> social_media <span class="sc">%&gt;%</span> </span>
<span id="cb75-2"><a href="testing-for-differences-between-groups.html#cb75-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">likes =</span>(bad_mood_likes <span class="sc">+</span> good_mood_likes)<span class="sc">/</span><span class="dv">2</span> ) <span class="co"># creates a new variable called likes which is the average of bad_mood_likes and good_mood_likes</span></span></code></pre></div>
<pre><code>##     X  id  age time_on_social urban good_mood_likes bad_mood_likes
## 1   1  S1 15.2           3.06     1            22.8           46.5
## 2   2  S2 16.0           2.18     1            46.0           48.3
## 3   3  S3 16.8           1.92     1            50.8           46.1
## 4   4  S4 15.6           2.61     1            29.9           29.2
## 5   5  S5 17.1           3.24     1            37.1           52.4
## 6   6  S6 15.7           2.44     1            26.9           20.2
## 7   7  S7 19.7           1.46     1            14.8           35.1
## 8   8  S8 18.6           1.52     1            26.0           35.8
## 9   9  S9 19.6           1.92     1             6.5           12.2
## 10 10 S10 15.5           2.10     1            45.7           32.8
##    followers polit_informed polit_campaign polit_activism likes
## 1      173.3            2.3            3.2            3.6 34.65
## 2      144.3            1.6            2.2            2.6 47.15
## 3       76.5            1.9            2.7            3.0 48.45
## 4      171.7            1.6            2.3            2.6 29.55
## 5      109.5            2.0            2.9            3.3 44.75
## 6      157.5            2.4            3.4            3.9 23.55
## 7      166.9            1.7            2.4            2.7 24.95
## 8      109.6            1.6            2.2            2.6 30.90
## 9      253.4            1.5            2.1            2.4  9.35
## 10      77.2            2.2            3.1            3.5 39.25</code></pre>
<p>You can see that <code>mutate()</code> has created an extra column called <code>likes</code>.</p>
<blockquote>
<p>Check that the values in the first three rows of the <code>likes</code> column match what you calculated and added to your comments. Talk to your tutor if they do not match.</p>
</blockquote>
<div style="border-left: 4px solid #33a02c; background-color: #a6cee3; padding: 10px; margin: 10px 0;">
<p><strong>Tip:</strong> Manually checking that a function has done what you think it should is a good habit to get into. It will help you catch bugs early on.</p>
</div>
<p>Now, this data frame has all we need for our analysis, and a lot more! Let’s make things simpler for ourselves by only keeping the variables we need. We can do this by once again using the pipe operator, along with the <code>select()</code> function.</p>
<blockquote>
<p>Update the code in your script so that it looks <strong>exactly</strong> like this:</p>
</blockquote>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="testing-for-differences-between-groups.html#cb77-1" tabindex="-1"></a>social_media_likes <span class="ot">&lt;-</span> social_media <span class="sc">%&gt;%</span> </span>
<span id="cb77-2"><a href="testing-for-differences-between-groups.html#cb77-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">likes =</span>(bad_mood_likes <span class="sc">+</span> good_mood_likes)<span class="sc">/</span><span class="dv">2</span> ) <span class="sc">%&gt;%</span> <span class="co"># creates a new variable called likes which is the average of bad_mood_likes and good_mood_likes</span></span>
<span id="cb77-3"><a href="testing-for-differences-between-groups.html#cb77-3" tabindex="-1"></a>  <span class="fu">select</span>(id, urban, likes, followers) <span class="co"># selects only the specified columns from the data frame</span></span></code></pre></div>
<blockquote>
<p>Check that the code did indeed select only the variables we want, by using the <code>head()</code> function to check what the new data frame called <code>social_media_likes</code> looks like.</p>
</blockquote>
<p>If you need help, there is an example for how to use the <code>head()</code> function in Section <a href="data-wrangling-and-visualisation.html#sec-data-view">2.6.1</a>.</p>
</div>
<div id="activity---defining-factors" class="section level3 hasAnchor" number="4.3.2">
<h3><span class="header-section-number">4.3.2</span> Activity - Defining factors<a href="testing-for-differences-between-groups.html#activity---defining-factors" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Now that we have this data frame object it is important to check that R can understand the data properly. Lets use the <code>str()</code> function that we learned about in Section <a href="data-wrangling-and-visualisation.html#sec-data-view">2.6.1</a> to examine what R thinks about each column.</p>
<blockquote>
<p>Complete the code in your script and run it, to make sure you get the same results.</p>
</blockquote>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="testing-for-differences-between-groups.html#cb78-1" tabindex="-1"></a><span class="fu">str</span>(social_media_likes) <span class="co">#provides a summary of the data structure.</span></span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    60 obs. of  4 variables:
##  $ id       : chr  &quot;S1&quot; &quot;S2&quot; &quot;S3&quot; &quot;S4&quot; ...
##  $ urban    : int  1 1 1 1 1 1 1 1 1 1 ...
##  $ likes    : num  34.6 47.1 48.5 29.5 44.8 ...
##  $ followers: num  173.3 144.3 76.5 171.7 109.5 ...</code></pre>
<p>What have we learned? We can see that R thinks that <code>urban</code> contains integers (int), i.e. R thinks that <code>urban</code> is a column of real numbers containing 1s and 2s. But <code>urban</code> is not a numeric variable, it is actually a factor (categorical variable).</p>
<p>If you remember from the README.txt file (which you read already, right? :)), <code>1</code> stands for urban and <code>2</code> stands for rural. We need to tell R this, so that it can understand how to work with this variable.</p>
<p>To do this, we can use the <code>factor()</code> function, which converts a variable to a factor. We also need to tell R that <code>1</code> means <code>urban</code> and <code>2</code> means <code>rural</code>.</p>
<p>Because we need the result to apply to every single <code>1</code> and <code>2</code> in rural, we need to use the <code>factor()</code> function along with a function that says “hey, let’s apply this to the whole column”. Remember how we use the <code>mutate()</code> function to make a new column? We can also apply the <code>mutate()</code> function to an existing column, as what ever you give it will be applied to every row of whichever column you name when using the function. The <code>mutate()</code> function is coming in handy today!</p>
<blockquote>
<p>Run the line of code in your script that matches this.</p>
</blockquote>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="testing-for-differences-between-groups.html#cb80-1" tabindex="-1"></a>social_media_likes <span class="ot">&lt;-</span> social_media_likes <span class="sc">%&gt;%</span> </span>
<span id="cb80-2"><a href="testing-for-differences-between-groups.html#cb80-2" tabindex="-1"></a>      <span class="fu">mutate</span>(<span class="at">urban =</span> <span class="fu">factor</span>(urban, <span class="at">levels=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>), <span class="at">labels=</span><span class="fu">c</span>(<span class="st">&#39;urban&#39;</span>, <span class="st">&#39;rural&#39;</span>))) <span class="co">#changes the urban variable to a factor with levels urban and rural</span></span></code></pre></div>
<p>Now we want to test that this code did what we wanted it to do.</p>
<blockquote>
<p>Use the <code>str()</code> function again to check that <code>urban</code> is now a factor.</p>
</blockquote>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="testing-for-differences-between-groups.html#cb81-1" tabindex="-1"></a><span class="fu">str</span>(social_media_likes)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    60 obs. of  4 variables:
##  $ id       : chr  &quot;S1&quot; &quot;S2&quot; &quot;S3&quot; &quot;S4&quot; ...
##  $ urban    : Factor w/ 2 levels &quot;urban&quot;,&quot;rural&quot;: 1 1 1 1 1 1 1 1 1 1 ...
##  $ likes    : num  34.6 47.1 48.5 29.5 44.8 ...
##  $ followers: num  173.3 144.3 76.5 171.7 109.5 ...</code></pre>
<p>Excellent! We can see that R now thinks that <code>urban</code> is a factor with 2 levels: <code>urban</code> and <code>rural</code>. Our data is now in a format that we should be able to easily visualise it and conduct our statistical tests. 90% done :)</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-40"></span>
<img src="images/Testing_between_groups/feels-like.gif" alt="What it feels like teaching this section" width="60%" />
<p class="caption">
Figure 4.1: What it feels like teaching this section
</p>
</div>
</div>
</div>
<div id="visualising-our-data" class="section level2 hasAnchor" number="4.4">
<h2><span class="header-section-number">4.4</span> Visualising our data<a href="testing-for-differences-between-groups.html#visualising-our-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>If you remember from Section <a href="sec-testing-first-hypothesis.html#sec-visualised-now-what">3.4.3</a>, we learned that we need to visualise our data to check if the distributions look roughly normal, and to check there are no obvious outliers or strange values that will impact our analysis.</p>
<p>Today, we are going to examine our variables using histograms. Just as we did in Section <a href="data-wrangling-and-visualisation.html#sec-make-histogram">2.11.5</a>. We have copied the code from Section <a href="data-wrangling-and-visualisation.html#sec-make-histogram">2.11.5</a> below, and have added a few options into the <code>geom_histogram()</code> function so that you can get a nice looking histogram. This code is also in your script.</p>
<div id="activity---adapting-our-previous-code-to-make-new-histograms" class="section level3 hasAnchor" number="4.4.1">
<h3><span class="header-section-number">4.4.1</span> Activity - Adapting our previous code to make new histograms<a href="testing-for-differences-between-groups.html#activity---adapting-our-previous-code-to-make-new-histograms" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Your challenge, should you choose to accept it*, is to change the code in your script so that you instead make a histogram for <code>likes</code> (<code>x=</code>) using the <code>social_media_likes</code> data frame (and not the <code>social_media_NA</code> data frame). Also remember to adjust the axis labels (the <code>x=</code> and <code>y=</code> arguments for <code>labs()</code>)!</p>
<blockquote>
<p>Change the below code in your own script to make the histogram for <code>likes</code>.</p>
</blockquote>
<p>*You have to accept it. Determinism beats free will.</p>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="testing-for-differences-between-groups.html#cb83-1" tabindex="-1"></a><span class="do">## health warning. This is old code that needs to be adapted for current purposes!</span></span>
<span id="cb83-2"><a href="testing-for-differences-between-groups.html#cb83-2" tabindex="-1"></a>social_media_NA <span class="sc">%&gt;%</span></span>
<span id="cb83-3"><a href="testing-for-differences-between-groups.html#cb83-3" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> )) <span class="sc">+</span> <span class="co">#ggplot uses aesthetic (aes()) to map axes. </span></span>
<span id="cb83-4"><a href="testing-for-differences-between-groups.html#cb83-4" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth=</span><span class="dv">10</span>, <span class="at">col=</span><span class="st">&quot;black&quot;</span>, <span class="at">fill=</span><span class="st">&quot;seagreen&quot;</span>) <span class="sc">+</span> <span class="co">#creates a histogram with blue fill, black borders, and a binwidth of 10</span></span>
<span id="cb83-5"><a href="testing-for-differences-between-groups.html#cb83-5" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Time on social media&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Density&quot;</span>) <span class="sc">+</span> <span class="co">#short for &quot;labels&quot;, use to label the axes.</span></span>
<span id="cb83-6"><a href="testing-for-differences-between-groups.html#cb83-6" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="co">#changes the theme of the plot to a classic theme. makes it prettier!</span></span></code></pre></div>
<p>You should get a histogram that looks something like this:</p>
<p><img src="_main_files/figure-html/do-hist-1.png" width="672" /></p>
<p>What would you say about this data, now you have looked at the histogram? Does it look normally distributed? Are there any outliers?</p>
<blockquote>
<p>Copy and paste the code you used to make the histogram for <code>likes</code> and make the teeny changes required so that you get a histogram for <code>followers</code> instead.</p>
</blockquote>
<p>Go on, you are a coder, and you are strong.</p>
<p><img src="_main_files/figure-html/do-hist-follow-1.png" width="672" /></p>
<div style="border-left: 4px solid #33a02c; background-color: #a6cee3; padding: 10px; margin: 10px 0;">
<p><strong>Question:</strong> Does <code>followers</code> look normally distributed to you? Why might the data be shaped how it is?</p>
</div>
<p>Indeed, the <code>followers</code> variable looks different to the <code>likes</code> variable. This is not too surprising. A fewer number of people in the sample have a huge number of followers, and the rest have a more modest number. Just like in real life. Random sampling works! Ahhh, science.</p>
<p>Because the <code>followers</code> variable is not normally distributed, we will need to be a bit cautious when interpreting the results of our t-test later on. But we can still proceed, as the t-test is quite robust to violations of normality. You would just make sure to mention this in your write-up, so that your readers also know.</p>
<p>However, we would reconsider this choice if <code>followers</code> contained a massive outlier, such as if we happened to sample someone with 10 million followers.</p>
</div>
</div>
<div id="next-step-descriptive-statistics" class="section level2 hasAnchor" number="4.5">
<h2><span class="header-section-number">4.5</span> Next step: descriptive statistics<a href="testing-for-differences-between-groups.html#next-step-descriptive-statistics" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Now that we know what shape our data is in, and when we should exercise caution, we can move on to generating some descriptive statistics of our key variables.</p>
<p>In Section <a href="sec-testing-first-hypothesis.html#sec-get-descriptive">3.5.1</a> we learned how to summarise our data to get descriptive statistics. Now you’ll get to see some more of the joy of coding - once you have written a bit of code that does something you need, its very easy to adapt it to do something else you need.</p>
<div id="activity---adapt-the-code-to-get-the-mean-and-standard-deviations-for-likes-and-followers" class="section level3 hasAnchor" number="4.5.1">
<h3><span class="header-section-number">4.5.1</span> Activity - Adapt the code to get the mean and standard deviations for likes and followers<a href="testing-for-differences-between-groups.html#activity---adapt-the-code-to-get-the-mean-and-standard-deviations-for-likes-and-followers" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Here is the code we wrote last week to get descriptive statistics of the rate of likes, grouped by mood:</p>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="testing-for-differences-between-groups.html#cb84-1" tabindex="-1"></a>social_media_likes <span class="sc">%&gt;%</span> </span>
<span id="cb84-2"><a href="testing-for-differences-between-groups.html#cb84-2" tabindex="-1"></a>  <span class="fu">group_by</span>(mood) <span class="sc">%&gt;%</span> <span class="co">#group the data by mood</span></span>
<span id="cb84-3"><a href="testing-for-differences-between-groups.html#cb84-3" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean =</span> <span class="fu">mean</span>(likes),</span>
<span id="cb84-4"><a href="testing-for-differences-between-groups.html#cb84-4" tabindex="-1"></a>            <span class="at">sd =</span> <span class="fu">sd</span>(likes)) <span class="co">#calculate the mean number of likes</span></span></code></pre></div>
<p>We want to use this code as a template for ourselves, so that we can get the mean and standard deviation for <code>likes</code> and <code>followers</code>, this time grouping by <code>urban</code>.</p>
<blockquote>
<p>You will find the below code in your script. Complete it to get the descriptive statistics for likes and followers.</p>
</blockquote>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="testing-for-differences-between-groups.html#cb85-1" tabindex="-1"></a>social_media_descriptives <span class="ot">&lt;-</span> social_media_likes <span class="sc">%&gt;%</span> <span class="co"># save to new object called social_media_descriptives</span></span>
<span id="cb85-2"><a href="testing-for-differences-between-groups.html#cb85-2" tabindex="-1"></a>  <span class="fu">group_by</span>(???) <span class="sc">%&gt;%</span> <span class="co"># group the data by urban</span></span>
<span id="cb85-3"><a href="testing-for-differences-between-groups.html#cb85-3" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb85-4"><a href="testing-for-differences-between-groups.html#cb85-4" tabindex="-1"></a>    <span class="at">mean_followers =</span> <span class="fu">mean</span>(followers), <span class="co"># calculate the mean number of followers for urban and rural groups separately</span></span>
<span id="cb85-5"><a href="testing-for-differences-between-groups.html#cb85-5" tabindex="-1"></a>    <span class="at">mean_likes =</span> <span class="fu">mean</span>(likes), <span class="co"># same for likes</span></span>
<span id="cb85-6"><a href="testing-for-differences-between-groups.html#cb85-6" tabindex="-1"></a>    <span class="at">sd_followers =</span> <span class="fu">sd</span>(???), <span class="co"># calculate the sd of followers</span></span>
<span id="cb85-7"><a href="testing-for-differences-between-groups.html#cb85-7" tabindex="-1"></a>    <span class="at">sd_likes =</span> <span class="fu">sd</span>(???) <span class="co"># calculate the sd of likes</span></span>
<span id="cb85-8"><a href="testing-for-differences-between-groups.html#cb85-8" tabindex="-1"></a>  )</span>
<span id="cb85-9"><a href="testing-for-differences-between-groups.html#cb85-9" tabindex="-1"></a></span>
<span id="cb85-10"><a href="testing-for-differences-between-groups.html#cb85-10" tabindex="-1"></a>social_media_descriptives</span></code></pre></div>
<blockquote>
<p>Check that your output for <code>social_media_descriptives</code> looks like this:</p>
</blockquote>
<pre><code>## # A tibble: 2 × 5
##   urban mean_followers mean_likes sd_followers sd_likes
##   &lt;fct&gt;          &lt;dbl&gt;      &lt;dbl&gt;        &lt;dbl&gt;    &lt;dbl&gt;
## 1 urban           144.       40.8         62.0     14.5
## 2 rural           106.       52.1         40.9     12.7</code></pre>
<blockquote>
<p>Look at the mean values you have generated for urban and rural dwellers. Are they what you expected? Do they fit with your predictions from earlier?</p>
</blockquote>
</div>
</div>
<div id="independent-samples-t-test" class="section level2 hasAnchor" number="4.6">
<h2><span class="header-section-number">4.6</span> Independent samples t-test<a href="testing-for-differences-between-groups.html#independent-samples-t-test" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Now we are down to the very last few percents of our 10% of analysis efforts. Let’s perform some independent samples t-tests to see if there are statistically significant differences between urban and rural dwellers in terms of their <code>likes</code> or <code>followers</code>.</p>
<div id="sec-formula-for-independence" class="section level3 hasAnchor" number="4.6.1">
<h3><span class="header-section-number">4.6.1</span> Activity - Performing independent samples t-tests<a href="testing-for-differences-between-groups.html#sec-formula-for-independence" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In Section <a href="sec-testing-first-hypothesis.html#sec-conducting-paired-t-test">3.7.1</a> we learned how to conduct a paired samples t-test. To do this, we had to deal with niggly base R demands and use the wideform data instead of our carefully wrangled longform data. Fortunately, the <code>t.test()</code> function is a bit more forgiving when it comes to independent samples t-tests, and we can use our longform data combined with a nifty thing that base R knows about, which is formulas. Huzzah.</p>
<p>This is how we use the formula method in <code>t.test()</code>. The syntax is <code>t.test(DV ~ IV, data = data frame)</code>. So, for our data, we want to test if the dependent variable (DV) <code>likes</code> differs by the independent variable (IV) of group that is coded in <code>urban</code>, using the <code>social_media_likes</code> data frame.</p>
<p>Note that you don’t need to set the <code>paired</code> argument to <code>FALSE</code>, as the <code>t.test()</code> function assumes this whenever you use the formula method. So never use the formula method for a paired samples t-test. That would be a disaster.</p>
<blockquote>
<p>Run the below line of code in your script, to check you get the same output.</p>
</blockquote>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="testing-for-differences-between-groups.html#cb87-1" tabindex="-1"></a><span class="fu">t.test</span>(likes<span class="sc">~</span>urban, <span class="at">data=</span>social_media_likes) <span class="co"># conducts an independent samples t-test to see if likes differ by urban/rural status</span></span></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  likes by urban
## t = -3.2184, df = 56.996, p-value = 0.002129
## alternative hypothesis: true difference in means between group urban and group rural is not equal to 0
## 95 percent confidence interval:
##  -18.338983  -4.271017
## sample estimates:
## mean in group urban mean in group rural 
##            40.78833            52.09333</code></pre>
<blockquote>
<p>What does the output of the independent t-test tell you about the differences between urban and rural dwellers and how they actively use social media? Is it what you expected when you formulated your hypothesis? Write a comment in your code that interprets your result in the context of your hypothesis.</p>
</blockquote>
<blockquote>
<p>What do the 95% CIs tell you about the mean difference between urban and rural dwellers in terms of likes? Write a comment in your code that interprets this.</p>
</blockquote>
<p>Is there a piece of extra information you would like to know about the difference between groups that is not provided in the output for the independent t-test? If you are unsure, ask your tutor. If you are, calculate the missing piece of information and add it as a comment in your code.</p>
<blockquote>
<p>Now complete the following line of code in your own script, to test if <code>followers</code> differ by <code>urban</code>.</p>
</blockquote>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="testing-for-differences-between-groups.html#cb89-1" tabindex="-1"></a><span class="fu">t.test</span>(???<span class="sc">~</span>urban, <span class="at">data=</span>social_media_likes) <span class="co"># conducts an independent samples t-test to see if followers differ by urban/rural status</span></span></code></pre></div>
<blockquote>
<p>Check your output with what you see below to make sure you got it right. Also, make sure to interpret what the output is telling you!</p>
</blockquote>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  followers by urban
## t = 2.8182, df = 50.234, p-value = 0.00689
## alternative hypothesis: true difference in means between group urban and group rural is not equal to 0
## 95 percent confidence interval:
##  10.98893 65.49107
## sample estimates:
## mean in group urban mean in group rural 
##            143.8767            105.6367</code></pre>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-41"></span>
<img src="images/Testing_between_groups/Exams-hard.jpg" alt="Every PSYC2001 midterm" width="50%" />
<p class="caption">
Figure 4.2: Every PSYC2001 midterm
</p>
</div>
</div>
</div>
<div id="writing-up-results-and-conclusions" class="section level2 hasAnchor" number="4.7">
<h2><span class="header-section-number">4.7</span> Writing up results and conclusions<a href="testing-for-differences-between-groups.html#writing-up-results-and-conclusions" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>This is how we would write up the results of an independent samples t-test.</p>
<div style="border-left: 4px solid #33a02c; background-color: #a6cee3; padding: 10px; margin: 10px 0;">
<p><strong>Results:</strong> An independent samples t-test indicated that the mean number of likes was greater for rural (<i>M</i> = 52.1 , <i>SD</i> = 12.7) compared to urban dwellers (<i>M</i> = 40.8 , <i>SD</i> = 14.5) and this difference was statistically significant (<i>t</i>(58) = 3.22, <i>p</i> = 0.002). Conversely, the mean number of followers was greater for urban (<i>M</i> = 143.9, <i>SD</i> = 62.0) than for urban dwellers (<i>M</i> = 105.6, <i>SD</i> = 40.9) which was statistically significant (<i>t</i>(58) = 2.82, <i>p</i> = 0.007).</p>
</div>
<div id="activity---visualising-group-differences" class="section level3 hasAnchor" number="4.7.1">
<h3><span class="header-section-number">4.7.1</span> Activity - Visualising group differences<a href="testing-for-differences-between-groups.html#activity---visualising-group-differences" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>If you have made it this far with time to spare, then kudos. Here are some extra skills that will be very helpful when you need to present results relating to group differences.</p>
<p>Earlier, we looked at the overall histograms for <code>likes</code> and <code>followers</code>. But when presenting our findings in a results section, what the reader really wants to see is how the groups differ from each other. One effective way to do this is to make a grouped boxplot. See <a href="https://www.simplypsychology.org/boxplots.html">here</a> for more details on boxplots.</p>
<p>Let’s make a boxplot, showing the <code>likes</code> data split by <code>urban</code> and <code>rural</code> groups. We are going to use a couple of new functions here (<code>geom_boxplot()</code>, <code>scale_fill_manual()</code>), which we explain in the comments below.</p>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb91-1"><a href="testing-for-differences-between-groups.html#cb91-1" tabindex="-1"></a>social_media_likes <span class="sc">%&gt;%</span> </span>
<span id="cb91-2"><a href="testing-for-differences-between-groups.html#cb91-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">y =</span> likes, <span class="at">group=</span>urban, <span class="at">fill =</span> urban, <span class="at">x =</span> urban)) <span class="sc">+</span> <span class="co"># here we are telling ggplot that we will be putting likes</span></span>
<span id="cb91-3"><a href="testing-for-differences-between-groups.html#cb91-3" tabindex="-1"></a>  <span class="co"># on the y axis, that we will fill in our boxplots with colour using the urban factor, and that urban will go on the x-axis</span></span>
<span id="cb91-4"><a href="testing-for-differences-between-groups.html#cb91-4" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span> <span class="co"># this function creates a boxplot</span></span>
<span id="cb91-5"><a href="testing-for-differences-between-groups.html#cb91-5" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Living Area&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Average Rate of Likes&quot;</span>) <span class="sc">+</span> <span class="co"># here we use labs() to label our axes.</span></span>
<span id="cb91-6"><a href="testing-for-differences-between-groups.html#cb91-6" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="at">rural =</span> <span class="st">&quot;plum&quot;</span>, <span class="at">urban =</span> <span class="st">&quot;cyan2&quot;</span>)) <span class="sc">+</span> <span class="co">#manually define the filled in colours of specific parts of a graph - see here for more R colours: https://r-graph-gallery.com/42-colors-names.html</span></span>
<span id="cb91-7"><a href="testing-for-differences-between-groups.html#cb91-7" tabindex="-1"></a>  <span class="fu">theme_classic</span>() </span></code></pre></div>
<p><img src="_main_files/figure-html/boxplotlikes-1.png" width="672" /></p>
<p>Now we return to another critical part of coding. Copying and pasting what you have, and changing just a few bits.</p>
<blockquote>
<p>Copy and paste the code above and change it to make a boxplot for <code>followers</code> instead of <code>likes</code>.</p>
</blockquote>
<p>You will need to change what you give for the <code>y</code> argument in <code>aes()</code>, and the y-axis label. You can also change the colours if you want to. A list of colours that can be used can be found <a href="https://r-graph-gallery.com/42-colors-names.html">here</a>.One you have finished, you should get something that looks like this:</p>
<p><img src="_main_files/figure-html/follow_bp-1.png" width="672" /></p>
<p>Last, we often want to save our figures as image files, so that we can include them in reports or presentations. This is very easy to do using the <code>ggsave()</code> function.</p>
<p>First, you should save the plot you want to save to an object.</p>
<blockquote>
<p>Amend your boxplot code so that the output saves to an object, such as you see below.</p>
</blockquote>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="testing-for-differences-between-groups.html#cb92-1" tabindex="-1"></a>likes_bp <span class="ot">&lt;-</span> social_media_likes <span class="sc">%&gt;%</span> </span>
<span id="cb92-2"><a href="testing-for-differences-between-groups.html#cb92-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">y =</span> likes, <span class="at">group=</span>urban, <span class="at">fill =</span> urban, <span class="at">x =</span> urban)) <span class="sc">+</span> </span>
<span id="cb92-3"><a href="testing-for-differences-between-groups.html#cb92-3" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span> <span class="co"># this function creates a boxplot</span></span>
<span id="cb92-4"><a href="testing-for-differences-between-groups.html#cb92-4" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Living Area&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Average Rate of Likes&quot;</span>) <span class="sc">+</span> <span class="co"># here we use labs() to label our axes.</span></span>
<span id="cb92-5"><a href="testing-for-differences-between-groups.html#cb92-5" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="at">rural =</span> <span class="st">&quot;plum&quot;</span>, <span class="at">urban =</span> <span class="st">&quot;cyan2&quot;</span>)) <span class="sc">+</span> </span>
<span id="cb92-6"><a href="testing-for-differences-between-groups.html#cb92-6" tabindex="-1"></a>  <span class="fu">theme_classic</span>() </span></code></pre></div>
<blockquote>
<p>Also amend your code for the <code>followers</code> boxplot so that it is saved to an object called <code>followers_bp</code>. Run the code and check the new object appears in the list in your Environment pane.</p>
</blockquote>
<p>Then, you can use the <code>ggsave()</code> function to save the plot to a file. The syntax is <code>ggsave("filename.png", plot = plot_name)</code>. You can change the file extension to save in different formats (e.g., .jpg, .pdf). We want to be extra smart and save the file to our <code>Output</code> folder, so we will use the <code>here()</code> function to specify the path.</p>
<blockquote>
<p>Copy and paste this code to your script, and run it. Then check the contents of the ‘Output’ folder.</p>
</blockquote>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="testing-for-differences-between-groups.html#cb93-1" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="fu">here</span>(<span class="st">&quot;Output&quot;</span>, <span class="st">&quot;likes_boxplot.png&quot;</span>), <span class="at">plot =</span> likes_bp) <span class="co"># saves the likes boxplot to the Output folder as a PNG file</span></span></code></pre></div>
<blockquote>
<p>Now copy and paste that, and change it so that you save your <code>followers_bp</code> plot instead of the <code>likes_bp</code> plot.</p>
</blockquote>
</div>
</div>
<div id="you-are-free-3" class="section level2 hasAnchor" number="4.8">
<h2><span class="header-section-number">4.8</span> You are Free!<a href="testing-for-differences-between-groups.html#you-are-free-3" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Well done! This computing tutorial is now over. Make sure to thank your tutor for another amazing class full of wonderful statistics and learning!</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-42"></span>
<img src="images/Testing_between_groups/Everyone-loves-statistics.jpg" alt="Everyone loves statistics ?" width="50%" />
<p class="caption">
Figure 4.3: Everyone loves statistics ?
</p>
</div>
</div>
<div id="bonus-exercises-2" class="section level2 hasAnchor" number="4.9">
<h2><span class="header-section-number">4.9</span> ⭐ Bonus exercises<a href="testing-for-differences-between-groups.html#bonus-exercises-2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>If that just wasn’t enough, then here are some extra coding challenges to defeat…</p>
<div id="bonus-activity---new-variable" class="section level3 hasAnchor" number="4.9.1">
<h3><span class="header-section-number">4.9.1</span> Bonus Activity - new variable!<a href="testing-for-differences-between-groups.html#bonus-activity---new-variable" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<blockquote>
<p>Create an extra variable called <code>engagement</code> which is the ratio of <code>likes</code> and <code>followers</code>. Then get the descriptive statistics for this new variable, grouped by <code>urban</code>.</p>
</blockquote>
<p>What can you learn about the distribution of this new variable? Can you analyse it by adapting the code from this session?</p>
</div>
<div id="bonus-activity---visualising-group-means" class="section level3 hasAnchor" number="4.9.2">
<h3><span class="header-section-number">4.9.2</span> Bonus Activity - Visualising group means<a href="testing-for-differences-between-groups.html#bonus-activity---visualising-group-means" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Before, we made boxplots to show the group differences between urban and rural dwellers. Boxplots are great, because they provide a good summary of the spread of the data. However, we make inference regarding the difference between group means, rather than the medians, and it is the group medians that the boxplots show. As the mean can be different to the median when the data are skewed, it can be helpful to add a point showing each group mean on top of the boxplots.</p>
<blockquote>
<p>Can you amend your code for your boxplots by using the <a href="https://ggplot2.tidyverse.org/reference/stat_summary.html"><code>stat_summary()</code></a> function?</p>
</blockquote>
</div>
<div id="bonus-activity---tracking-bugs" class="section level3 hasAnchor" number="4.9.3">
<h3><span class="header-section-number">4.9.3</span> Bonus Activity - Tracking bugs<a href="testing-for-differences-between-groups.html#bonus-activity---tracking-bugs" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Here we will have a go at identifying when code has not worked perhaps as we thought it would. This challenge is a little fiendish, but I am sure you can do it.</p>
<blockquote>
<p>Copy the following line of code into your script and run it. You should see the same data as below. Can you work out what went wrong with the <code>new_likes</code> variable?</p>
</blockquote>
<p>Can you write the code that proves what is wrong?</p>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="testing-for-differences-between-groups.html#cb94-1" tabindex="-1"></a>social_media <span class="sc">%&gt;%</span> </span>
<span id="cb94-2"><a href="testing-for-differences-between-groups.html#cb94-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">new_likes =</span> <span class="fu">mean</span>(<span class="fu">c</span>(good_mood_likes, bad_mood_likes)))</span></code></pre></div>
<pre><code>##     X  id  age time_on_social urban good_mood_likes bad_mood_likes
## 1   1  S1 15.2           3.06     1            22.8           46.5
## 2   2  S2 16.0           2.18     1            46.0           48.3
## 3   3  S3 16.8           1.92     1            50.8           46.1
## 4   4  S4 15.6           2.61     1            29.9           29.2
## 5   5  S5 17.1           3.24     1            37.1           52.4
## 6   6  S6 15.7           2.44     1            26.9           20.2
## 7   7  S7 19.7           1.46     1            14.8           35.1
## 8   8  S8 18.6           1.52     1            26.0           35.8
## 9   9  S9 19.6           1.92     1             6.5           12.2
## 10 10 S10 15.5           2.10     1            45.7           32.8
##    followers polit_informed polit_campaign polit_activism new_likes
## 1      173.3            2.3            3.2            3.6  46.44083
## 2      144.3            1.6            2.2            2.6  46.44083
## 3       76.5            1.9            2.7            3.0  46.44083
## 4      171.7            1.6            2.3            2.6  46.44083
## 5      109.5            2.0            2.9            3.3  46.44083
## 6      157.5            2.4            3.4            3.9  46.44083
## 7      166.9            1.7            2.4            2.7  46.44083
## 8      109.6            1.6            2.2            2.6  46.44083
## 9      253.4            1.5            2.1            2.4  46.44083
## 10      77.2            2.2            3.1            3.5  46.44083</code></pre>
<p>Bug defeated? Achievement unlocked!</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="sec-testing-first-hypothesis.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="probing-statistical-relationships-with-correlation-analysis.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/04_Testing-between-groups.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
